name: Build Universal macOS Wheels
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build_universal_wheels:
    name: Build ${{ matrix.python.py_ver }}-macosx_universal2
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - { py_ver: cp38, py_version: '3.8' }
          - { py_ver: cp39, py_version: '3.9' }
          - { py_ver: cp310, py_version: '3.10' }
          - { py_ver: cp311, py_version: '3.11' }
          - { py_ver: cp312, py_version: '3.12' }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python ${{ matrix.python.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.py_version }}
          check-latest: true

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build Universal Wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python.py_ver }}-macosx_universal2
          CIBW_ARCHS_MACOS: universal2
          CIBW_BEFORE_BUILD: "pip install -r requirements.txt"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/tests
          CIBW_ENVIRONMENT: |
            CFLAGS='-O3 -g0 -mtune=generic -pipe -fPIC'
            LDFLAGS='-fPIC'
