name: pip_install_unitest
on:
  workflow_dispatch:
    inputs:
      install_prerelease:
        description: 'Check this to install the prerelease version of quicksectx if available and the version is newer than formal release.'  
        type: boolean   
        required: false
        default: false


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python-version }}-${{ matrix.buildplat[1] }}
    if: >-
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'Build System'))
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
        - [ ubuntu-latest, ubuntu-latest]
        - [ macos-latest, macosx_latest ]
        - [ windows-latest, windows-latest ]
        #        spacy doesn't compile win32
        #        python: ["cp36"] # Note: Wheels not needed for PyPy
        python-version: [ "3.8", "3.9","3.10","3.11"] # Note: Wheels not needed for PyPy
        # python-version: [ "3.7"]
    timeout-minutes: 45
    steps:
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: remove source code
        run: |
          pwd
          ls
          python -c "import shutil;shutil.rmtree('quicksectx')"
          ls



      - name: Install pre-release
        if: ${{ github.event.inputs.install_prerelease == 'true' }} 
        run: |
          python -m pip install --upgrade pip
          pip install --pre quicksectx pytest

      - name: Install regular release
        if: ${{ github.event.inputs.install_prerelease == 'false' }} 
        run: |
          python -m pip install --upgrade pip
          pip install quicksectx pytest

      - name: run pytest
        run: |                            
          ls
          python --version
          pytest tests


  
