name: test build
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build ${{ matrix.python.py_ver }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-latest, manylinux_x86_64]
          - [macos-latest, macosx_x86_64]
          - [windows-latest, win_amd64]
        python:
          - { py_ver: cp38, py_version: '3.8' }
          - { py_ver: cp39, py_version: '3.9' }
          - { py_ver: cp310, py_version: '3.10' }
          - { py_ver: cp311, py_version: '3.11' }
          - { py_ver: cp312, py_version: '3.12' }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python.py_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.py_version }}

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.21.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: "pip install -r requirements.txt"
          CIBW_BUILD: ${{ matrix.python.py_ver }}-${{ matrix.buildplat[1] }}
          CIBW_ENVIRONMENT: |
            CFLAGS='-O3 -g0 -mtune=generic -pipe -fPIC'
            LDFLAGS='-fPIC'
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests
          CIBW_ARCHS_MACOS: x86_64  # Specify architecture for macOS

      - name: Check build
        run: ls -l wheelhouse